tags: 
  - task
summary: "Create a new task entry"
description: "Add a new task to the database"
consumes:
  - application/json
produces:
  - application/json
parameters:
  - in: body
    name: task
    description: Task object to create 
    required: true 
    schema:
      $ref: "#/definitions/TaskCreate"
responses:
  201: 
    description: "Task created Successfully"
    schema:   
      $ref: "#/definitions/TaskCreate"
  400:
    description: "Invalid Input"
  409:
    description: "Task already exists"
  500:
    description: "Internal Server Error"