tags:
  - tasks
produces:
  - application/json
summary: "List tasks with pagination"
description: "Retrieve a paginated list of tasks."
parameters:
  - name: page
    in: query
    type: integer
    default: 1
    description: Page number (optional)
  - name: per_page
    in: query
    type: integer
    default: 20
    description: Items per page (optional, max 100)
responses:
  200:
    description: "Paginated list of tasks"
    schema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/definitions/Task"
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
        pages:
          type: integer
